apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ngnix-deploy
  name: ngnix-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ngnix-deploy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ngnix-deploy
    spec:
      containers:
      - image: nginx:1.29-perl
        name: nginx
#        command: ["/bin/bash", "-c"]
#        args: ["sleep 5;exit 1"]
