apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ngnix-deploy
  name: ngnix-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ngnix-deploy
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: ngnix-deploy
    spec:
      containers:
      - image: nginx:1.29-perl
        name: nginx
